[buildPlans.IosevkaCustomSlab]
family = "Iosevka Custom Slab"
spacing = "normal"
serifs = "slab"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaCustomSlab.variants.design]
zero = "dotted"
lig-equal-chain = "without-notch"

  [buildPlans.IosevkaCustomSlab.ligations]
  inherits = "javascript"

[buildPlans.IosevkaCustomSlab.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustomSlab.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCustomSlab.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaCustomSlab.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaCustomSlab.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.IosevkaCustomSlab.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaCustomSlab.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCustomSlab.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
